version: '3'

services:
    inescoin_node:
        container_name: inescoin-node
        hostname: inescoin-node
        restart: always
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: Europe/Madrid
        volumes:
            - ./:/opt/
        ports:
            - "3031:3031"
            - "3030:3030"
            - "8087:8087"
            - "8088:8088"
            - "8086:8086"
            - "8180:8180"
        stdin_open: true
        expose:
            - "3031"
            - "3030"
            - "8087"
            - "8088"
            - "8086"
            - "8180"
        networks:
            - overlay
    inescoin_explorer_nginx:
        build: ../inescoin-explorer/docker/nginx
        container_name: inescoin-explorer-nginx
        hostname: inescoin-explorer-nginx
        restart: always
        working_dir: /www
        volumes:
            - ../inescoin-explorer/:/www
        ports:
            - "8000:80"
        networks:
            - overlay
    inescoin_explorer_phpfpm:
        build: ../inescoin-explorer/docker/phpfpm
        container_name: inescoin-explorer-phpfpm
        hostname: inescoin-explorer-phpfpm
        restart: always
        working_dir: /www
        volumes:
            - ../inescoin-explorer/:/www
        networks:
            - overlay
    inescoin_website_nginx:
        build: ../inescoin-website-viewer/docker/nginx
        container_name: inescoin-website-viewer-nginx
        hostname: inescoin-website-viewer-nginx
        restart: always
        working_dir: /www
        volumes:
            - ../inescoin-website-viewer/:/www
        ports:
            - "8001:80"
        networks:
            - overlay
    inescoin_website_phpfpm:
        build: ../inescoin-website-viewer/docker/phpfpm
        container_name: inescoin-website-viewer-phpfpm
        hostname: inescoin-website-viewer-phpfpm
        restart: always
        working_dir: /www
        volumes:
            - ../inescoin-website-viewer/:/www
        networks:
            - overlay
networks:
    overlay:
